title: 离世庭院
subtitle: To be a builder,not a imitator
link: Homepage link
meta:
  description: Content of description meta tag
  keywords: !!seq
    - 代码
    - 数据库
    - 信息安全
  author: Content of author meta tag
master:
  name: Ario
  about: Coder
  email: zxdy@vip.qq.com
rss:
  title: RSS feed title
  desc: RSS feed description
  lang: zh-cn
  max: 10
copyright:
  owner: Ario
  beginYear: 2011
  endYear: 2014
theme: default
codetheme: night
